[package]
name = "tea_todo"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
clap = "4.0.29"
colored = "2.0.0"
ron = "0.8.0"
serde = { version = "1.0.149", features = ["derive"] }
xdg = "2.4.1"
